name: Event Types
on:
  pull_request:
    types: 
      - opened
    branches:
      - main
      - 'dev-*' # branch starts with 'dev-' eg: dev-new  dev-modal
      - 'feat/**' # feat/modal feat/ui/button
  workflow_dispatch: 
  push:
    branches:
      - main
      - 'dev-*' # branch starts with 'dev-' eg: dev-new  dev-modal
      - 'feat/**' # feat/modal feat/ui/button
    paths-ignore: 
      - '.github/workflows/*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3