name: Event Types
on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch: 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3